"""add foreign key to Review

Revision ID: aa2e92be97de
Revises: c04840c9ab67
Create Date: 2024-10-03 18:58:45.951107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2e92be97de'
down_revision = 'c04840c9ab67'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
#     # ### end Alembic commands ###

def upgrade():
    # Use batch mode to modify the reviews table
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f('fk_reviews_employee_id_employees'),
            'employees', ['employee_id'], ['id']
        )

def downgrade():
    # Use batch mode to drop the foreign key
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_employee_id_employees'), type_='foreignkey')
